export const items = [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile App Developer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "AI Engineer",
    "Cybersecurity Analyst",
    "Penetration Tester",
    "Security Engineer",
    "Blockchain Developer",
    "Game Developer",
    "UI/UX Designer",
    "Web Developer",
    "Site Reliability Engineer (SRE)",
    "Product Manager",
    "Technical Support Engineer",
    "QA Engineer / Test Automation Engineer",
    "Database Administrator",
    "System Administrator",
    "IT Consultant",
    "Embedded Systems Engineer",
    "Computer Vision Engineer",
    "Natural Language Processing (NLP) Engineer",
    "Research Scientist (AI/ML)",
    "Network Engineer",
    "IT Project Manager",
    "Business Intelligence Analyst",
    "Robotics Engineer",
    "AR/VR Developer",
    "Big Data Engineer",
    "Software QA Tester",
    "Game Designer",
    "Technical Writer",
    "Solutions Architect",
    "CRM Developer (e.g., Salesforce)",
    "ERP Consultant (e.g., SAP, Oracle)",
    "Technical Program Manager",
    "Data Engineer",
    "Firmware Engineer",
  ];